<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <!-- Added RuntimeIdentifiers for auto-publish. 2026-08-29. DjD -->
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Copyright>© 2026 Capillume</Copyright>
    <PackageProjectUrl>https://github.com/dasdebjyoti/Capillume</PackageProjectUrl>
    <Description>Lightweigt screenshot automation tool for Windows.</Description>
    <RepositoryType>git</RepositoryType>
    <PackageTags>screenshot; screen-shot; screen-capture; productivity</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <Title>Capillume Screenshot Automation</Title>
    <AssemblyVersion>1.3.0.0</AssemblyVersion>
    <FileVersion>1.3.0.0</FileVersion>
    <Version>1.3.0</Version>

    <!-- Uncomment to force SkiaSharp to be bundled inside the published application exe -->
    <!-- Added DjD.20260823 -->
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

    <!-- Optional: remove PDB during publish -->
    <!-- Added DjD.20260823 -->
    <!--<DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>-->
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <!-- Added for auto-publish. 2026-08-29. DjD -->
  <Target Name="PublishForInstaller"
          AfterTargets="Build"
          Condition="'$(Configuration)' == 'Release' and '$(PublishForInstallerRunning)' != 'true'">

    <MSBuild Projects="$(MSBuildProjectFullPath)"
             Targets="Publish"
             Properties="Configuration=$(Configuration);
                         RuntimeIdentifier=win-x64;
                         SelfContained=true;
                         PublishSingleFile=true;
                         PublishDir=$(MSBuildProjectDirectory)\bin\$(Configuration)\$(TargetFramework)\publish\win-x64\;
                         PublishForInstallerRunning=true" />
  </Target>
</Project>